# Generated by Django 3.2.12 on 2022-09-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(max_length=64)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=128)),
                ('mobile', models.IntegerField()),
                ('nic', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
