# Generated by Django 3.2.12 on 2022-09-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='house',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='pipe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='roof',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
